// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayfidvycgqorxmlczyxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5ZmlkdnljZ3FvcnhtbGN6eXhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwMDM1MjYsImV4cCI6MjA4OTU3OTUyNn0.8gkp-NeR3KOKkKrj-FSyo-mcsSR19Rr3lMSU8qFzXN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});